Add popup
matee-safi/matee-safi.github.io pull request #4
Opened 2023-02-02 13:17 UTC by matee-safi

# A short summary of what I did:
- create a new branch
- add a popup for mobile
- add a popup for desktop
- commit changes and push
- create a new pull request

2023-02-02 13:44 UTC, IngDavidTM requested changes
## Hi @matee-safi  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 13:44 UTC, IngDavidTM commented on index.html
> +    </div>
- [ ] While you did a good job creating the popup :+1:, I think it is one of the [main requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) to create dynamically the popup and the original cards that you previously created in HTML by using javascript so kindly remove all the code for all the cards from the HTML (the projects/works section) and create it by using JS. It would help you to learn how to create HTML by JS :100:. [Here](https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95) you can find a good example of it.

2023-02-02 13:44 UTC, IngDavidTM commented on script.js
> +closeCrossDesktop.addEventListener('click', closePopup);
- [ ] You did an amazing job adding the required JS to your popup :+1:, but as a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) the JavaScript code should implement an array of objects to store JavaScript objects containing information like, name, description, featured image, technologies, link to live version, and link, for each project (Works section). You can see an example below.

```javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```

Kindly don't forget that the modal popup data should be populated with the data from the `projects` array.

2023-02-02 18:03 UTC, matee-safi commented on index.html
> +    </div>
Thank you, I created all the files you mentioned with javascript but now the functionality of the buttons are now lost

2023-02-03 13:12 UTC, IngDavidTM requested changes
## Hi @matee-safi  🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 02:15 UTC, BenMukebo requested changes
Hi @Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions


``` ## Authors ```

- [OPTIONAL] Update your Readme, This is a group project. Please let's include all the authors in the README file. This makes the README file professional and descriptive. 👨🏻‍🎨 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 02:15 UTC, BenMukebo commented on index.html
> +                        <button>See Live<img src="./assets/Icon - Export Desktop.png" alt="export"></button>
- [ ] As requested by the previous reviewer, In this particular project, the section of the whole project along with the models should be created dynamically with Javascript. I can see that the base projects section data is populated with the data from the `projectData`  array a good job! 👏🏻 , but the Modal popup data is still not being created with Javascript.  Please use Javascript to dynamically render your Modals or Popup windows section as you did with the base projects section page.

- That way, adding projects in the future will be easy. You will only need to add it in one place - as another object in the `arrayCards` array. 😉 👍🏻 
 
 - (Note: the works section and the Modal popup section must be removed from HTML and generated with javascript )


https://github.com/matee-safi/matee-safi.github.io/blob/9081d7eb1017d18a3f9b24d2c0dee29b6c97635a/index.html#L133-L199

2023-02-04 02:15 UTC, BenMukebo commented on script.js
> +  id: 1,
- [ ] Your work project section is not displayed well on my side kindly ix this 👇🏻 

![image](https://user-images.githubusercontent.com/79058364/216741100-ff8c7e56-22e0-4123-8bbb-8a5b41ad4c5a.png)

2023-02-04 13:23 UTC, matee-safi commented on script.js
> +  id: 1,
Hi @BenMukebo, I applied everything you suggested except this part, I don't know what to do about it because it worked perfectly fine on my side and also on my coding partner's side, could you please help me out because I only have one extra review and it's my last one.

2023-02-04 13:47 UTC, matee-safi commented
@BenMukebo, I am not able to find the linter check problem, they all look fine to me, could please help me with that?

2023-02-04 16:30 UTC, EricMbouwe approved these changes
Hi @matee-safi, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Requested changes ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 16:47 UTC, merged

2023-02-06 01:37 UTC, BenMukebo commented on script.js
> +  id: 1,
Hello @matee-safi, sorry for the late reply however I can see that the project is alrady approved 🥳 Congratulation guys 👍🏻